name: Create Business Page

on:
  repository_dispatch:
    types: [create-business-page]

jobs:
  create-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Business Directory
        run: |
          mkdir -p businesses/${{ github.event.client_payload.slug }}
          
      - name: Create Business Page
        run: |
          cat > businesses/${{ github.event.client_payload.slug }}/index.html << EOL
          
          
          
              
              
              
              
              
          
          
              
              

                  
${{ github.event.client_payload.name }}

                  
                  

                      
${{ github.event.client_payload.name }}

                      
                      
                      

                          
                      

                  

                  
                  

                      
Powered by CK Marketing Ltd


                  

              

              
              
          
          
          EOL
          
      - name: Update Business Config
        run: |
          # Update config.json with new business info
          # This would require a more complex script in practice
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add payment page for ${{ github.event.client_payload.name }}"
          git push
